"""update admin model with named constraint

Revision ID: 950cd4ea4b4c
Revises: 
Create Date: 2026-03-12 11:47:53.275177

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '950cd4ea4b4c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_name', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('last_name', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('email', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('password_hash', sa.String(length=128), nullable=False))
        batch_op.add_column(sa.Column('is_approved', sa.Boolean(), nullable=True))
        batch_op.create_index(batch_op.f('ix_admins_email'), ['email'], unique=True)
        batch_op.create_unique_constraint('uq_admin_email', ['email'])
        batch_op.drop_column('password')
        batch_op.drop_column('userName')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.add_column(sa.Column('userName', sa.TEXT(), nullable=False))
        batch_op.add_column(sa.Column('password', sa.TEXT(), nullable=False))
        batch_op.drop_constraint('uq_admin_email', type_='unique')
        batch_op.drop_index(batch_op.f('ix_admins_email'))
        batch_op.drop_column('is_approved')
        batch_op.drop_column('password_hash')
        batch_op.drop_column('email')
        batch_op.drop_column('last_name')
        batch_op.drop_column('first_name')

    # ### end Alembic commands ###
