"""add quantity

Revision ID: f425c9032e45
Revises: a4a3c9349df6
Create Date: 2026-03-05 11:00:34.437230

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f425c9032e45'
down_revision = 'a4a3c9349df6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bathrobes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quantity', sa.Integer(), nullable=False))

    with op.batch_alter_table('nightdress', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quantity', sa.Integer(), nullable=False))

    with op.batch_alter_table('pajamas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quantity', sa.Integer(), nullable=False))

    with op.batch_alter_table('rompers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quantity', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rompers', schema=None) as batch_op:
        batch_op.drop_column('quantity')

    with op.batch_alter_table('pajamas', schema=None) as batch_op:
        batch_op.drop_column('quantity')

    with op.batch_alter_table('nightdress', schema=None) as batch_op:
        batch_op.drop_column('quantity')

    with op.batch_alter_table('bathrobes', schema=None) as batch_op:
        batch_op.drop_column('quantity')

    # ### end Alembic commands ###
